import { Course } from '@/types'

export const courses: Course[] = [
  {
    id: '1',
    title: 'Python Mastery',
    description: 'From zero to Python hero. Build real projects with clean, professional code.',
    category: 'Programming',
    level: 'Beginner',
    lessons: 48,
    duration: '12 hours',
    price: 49,
    image: '/courses/python.png',
    slug: 'python-mastery',
    tags: ['Python', 'Automation', 'Data'],
    featured: true,
  },
  {
    id: '2',
    title: 'Linux for Developers',
    description: 'Master the terminal, shell scripting, and system administration.',
    category: 'DevOps',
    level: 'Intermediate',
    lessons: 36,
    duration: '9 hours',
    price: 39,
    image: '/courses/linux.png',
    slug: 'linux-for-developers',
    tags: ['Linux', 'Bash', 'Shell'],
  },
  {
    id: '3',
    title: 'Git & GitHub Pro',
    description: 'Version control, collaboration workflows, and open source contribution.',
    category: 'Tools',
    level: 'Beginner',
    lessons: 24,
    duration: '6 hours',
    price: 29,
    image: '/courses/git.png',
    slug: 'git-github-pro',
    tags: ['Git', 'GitHub', 'CI/CD'],
  },
  {
    id: '4',
    title: 'Cloud Engineering',
    description: 'Deploy, scale, and manage applications on AWS, GCP, and Azure.',
    category: 'Cloud',
    level: 'Advanced',
    lessons: 52,
    duration: '15 hours',
    price: 69,
    image: '/courses/cloud.png',
    slug: 'cloud-engineering',
    tags: ['AWS', 'Docker', 'Kubernetes'],
  },
  {
    id: '5',
    title: 'Chess Strategy & Tactics',
    description: 'Think like a grandmaster. Learn openings, tactics, and endgame theory.',
    category: 'Chess',
    level: 'Intermediate',
    lessons: 30,
    duration: '8 hours',
    price: 34,
    image: '/courses/chess.png',
    slug: 'chess-strategy',
    tags: ['Chess', 'Strategy', 'Tactics'],
  },
  {
    id: '6',
    title: 'AI & Prompt Engineering',
    description: 'Build AI-powered apps and master the art of working with LLMs.',
    category: 'AI',
    level: 'Intermediate',
    lessons: 40,
    duration: '10 hours',
    price: 59,
    image: '/courses/ai.png',
    slug: 'ai-prompt-engineering',
    tags: ['AI', 'LLM', 'ChatGPT'],
    featured: true,
  },
]

export const plans = [
  {
    id: 'starter',
    name: 'Starter',
    price: 0,
    interval: 'month' as const,
    features: [
      'Access to 2 free courses',
      'Community forum access',
      'Course previews',
      'Mobile access',
    ],
    stripePriceId: '',
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 19,
    interval: 'month' as const,
    features: [
      'All 6 courses unlocked',
      'Certificate of completion',
      'Progress tracking',
      'Priority support',
      'New courses as added',
      'Download for offline',
    ],
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRO_PRICE_ID || '',
    popular: true,
  },
  {
    id: 'lifetime',
    name: 'Lifetime',
    price: 199,
    interval: 'month' as const,
    features: [
      'Everything in Pro',
      'Lifetime access — pay once',
      'All future courses free',
      '1-on-1 mentoring session',
      'Private community access',
      'Early access to new content',
    ],
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_LIFETIME_PRICE_ID || '',
  },
]
